@startuml US10-DM
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

class Journalist {
    name
    email
    phone
    pressCardNumber
}

class "Political Agent" as PoliticalAgent {
    name
    email
    nationalIdentityCard
    taxIdentificationNumber
    politicalFunction
    mandateStart
    mandateEnd
}

class "Declaration of Interests" as Declaration {
    id
    name
    submissionDate
}

enum DeclarationStatus {
    pending
    validated
    rejected
}

enum Type {
    initial
    regular
    exceptional
}

enum PoliticalFunction {
    minister
    deputy
    councillor
    parishCouncilPresident
    mayor
}

class Income {
    amount
    source
    institution
    date
}

Journalist "*" -- "*" PoliticalAgent : analyses income of

PoliticalAgent "*" -- "*" Declaration : has

PoliticalAgent "1" -- "1" PoliticalFunction : has

Declaration "1" -- "1" Type : has
Declaration "1" -- "1" DeclarationStatus : has
Declaration "1" -- "*" Income : has

@enduml
