@startuml US09-SD-partial-aggregate-integrated-situation
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Ethics Committee Member" as ECM
participant ":ConsultIntegratedSituationUI" as UI
participant "dto:DeclarationDTO" as DEC

autonumber 9
 -> UI : display declarations
autonumber 9.1
activate UI
    group Display Declarations

        loop for each d in declarations
            UI -> DEC : getPositions()
            activate DEC
                DEC --> UI : positionEntries
            deactivate DEC

            UI -> DEC : getIncomes()
            activate DEC
                DEC --> UI : incomes
            deactivate DEC

            UI -> DEC : getSubsidies()
            activate DEC
                DEC --> UI : subsidyEntries
            deactivate DEC

            UI -> DEC : getAssets()
            activate DEC
                DEC --> UI : assetEntries
            deactivate DEC

            UI -> DEC : getBusinessParticipations()
            activate DEC
                DEC --> UI : participations
            deactivate DEC
        end

        UI --> ECM : shows positions, incomes,\nsubsidies, assets, participations

    end
deactivate UI

@enduml
