@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US04

autonumber

actor "Administrator" as Admin
participant ":System" as System

activate Admin

Admin -> System : asks to register a new institution
activate System
System --> Admin : requests data (name, type)
deactivate System

Admin -> System : types name and type
activate System
System --> Admin : requests nature (public, private, social)
deactivate System

Admin -> System : selects nature
activate System
System --> Admin : informs operation success
deactivate System

deactivate Admin

@enduml