@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US04

autonumber

actor "Administrator" as Admin
participant ":System" as System

activate Admin

Admin -> System : asks to register a new organization
activate System
System --> Admin : shows organization type list\n(Company, Political Party, Foundation, Institute, Association)\nand requests selection
deactivate System

Admin -> System : selects organization type
activate System
System --> Admin : requests organization name
deactivate System

Admin -> System : types organization name
activate System
System --> Admin : shows data and requests confirmation
deactivate System

Admin -> System : confirms
activate System
System --> Admin : displays operation success
deactivate System

deactivate Admin

@enduml
