@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Citizen/Journalist" as User
participant ":System" as System

activate User

    User -> System : asks to consult assets of a political agent
    activate System

        System --> User : requests agent name and reference date
    deactivate System

    User -> System : enters agent name and reference date
    activate System

        System --> User : shows assets from validated declarations\nup to the specified date\n(sensitive data filtered by user role)

    deactivate System

deactivate User
@enduml
