@startuml US12-SD
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Citizen" as C
participant ":SubmitComplaintUI" as UI
participant ":SubmitComplaintController" as CTRL
participant "Repositories" as REPOS
participant ":PoliticalAgentRepository" as PAR
participant ":AuthenticationRepository" as AR
participant "session:UserSession" as SESS
participant "email:Email" as EML
participant ":CitizenRepository" as CitR
participant ":ComplaintRepository" as CR
participant "cpl:Complaint" as CPL

activate C

    C -> UI : requests to submit a complaint
    activate UI

        UI -> CTRL** : create
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS
            CTRL -> REPOS : getPoliticalAgentRepository()
            activate REPOS
                REPOS --> CTRL : politicalAgentRepository
            deactivate REPOS
            CTRL -> REPOS : getCitizenRepository()
            activate REPOS
                REPOS --> CTRL : citizenRepository
            deactivate REPOS
            CTRL -> REPOS : getComplaintRepository()
            activate REPOS
                REPOS --> CTRL : complaintRepository
            deactivate REPOS
            CTRL -> REPOS : getAuthenticationRepository()
            activate REPOS
                REPOS --> CTRL : authenticationRepository
            deactivate REPOS
        deactivate CTRL

        UI -> CTRL : getPoliticalAgents()
        activate CTRL
            CTRL -> PAR : getAll()
            activate PAR
                PAR --> CTRL : politicalAgentList
            deactivate PAR
            CTRL --> UI : politicalAgentList
        deactivate CTRL

        UI --> C : shows list of political agents\nand asks to select one
    deactivate UI

    C -> UI : selects political agent
    activate UI

        UI -> CTRL : getPoliticalFunctions()
        activate CTRL
            CTRL --> UI : politicalFunctionList
        deactivate CTRL

        UI --> C : shows list of political functions\nand asks to select one
    deactivate UI

    C -> UI : selects political function
    activate UI
        UI --> C : requests complaint description and date
    deactivate UI

    C -> UI : types description and date
    activate UI
        UI --> C : shows complaint summary and requests confirmation
    deactivate UI

    C -> UI : confirms
    activate UI

        UI -> CTRL : submitComplaint(description, date, politicalAgent, politicalFunction)
        activate CTRL

            CTRL -> AR : getCurrentUserSession()
            activate AR
                AR --> CTRL : session
            deactivate AR

            CTRL -> SESS : getUserId()
            activate SESS
                SESS --> CTRL : email
            deactivate SESS

            CTRL -> EML : getEmail()
            activate EML
                EML --> CTRL : emailAddress
            deactivate EML

            CTRL -> CitR : getCitizenByEmail(emailAddress)
            activate CitR
                CitR --> CTRL : citizen
            deactivate CitR

            CTRL -> CPL ** : new Complaint(description, date, citizen, politicalAgent, politicalFunction)

            CTRL -> CR : save(complaint)
            activate CR
                CR --> CTRL : success
            deactivate CR

            CTRL --> UI : success
        deactivate CTRL

        UI --> C : displays operation success
    deactivate UI

deactivate C

@enduml
