@startuml US12-SD
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Citizen" as C
participant ":SubmitComplaintUI" as UI
participant ":SubmitComplaintController" as CTRL
participant "Repositories" as REPOS
participant ":PoliticalAgentMapper" as PAM
participant ":PoliticalAgentRepository" as PAR
participant ":AuthenticationRepository" as AR
participant "session:UserSession" as SESS
participant ":CitizenRepository" as CitR
participant ":ComplaintRepository" as CR
participant "cpl:Complaint" as CPL

activate C

    C -> UI : requests to submit a complaint
    activate UI

        UI -> CTRL** : create
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS
            CTRL -> REPOS : getPoliticalAgentRepository()
            activate REPOS
                REPOS --> CTRL : politicalAgentRepository
            deactivate REPOS
            CTRL -> REPOS : getCitizenRepository()
            activate REPOS
                REPOS --> CTRL : citizenRepository
            deactivate REPOS
            CTRL -> REPOS : getComplaintRepository()
            activate REPOS
                REPOS --> CTRL : complaintRepository
            deactivate REPOS
            CTRL -> REPOS : getAuthenticationRepository()
            activate REPOS
                REPOS --> CTRL : authenticationRepository
            deactivate REPOS
        deactivate CTRL

        UI -> CTRL : getPoliticalAgents()
        activate CTRL
            CTRL -> PAR : getAll()
            activate PAR
                PAR --> CTRL : politicalAgentList
            deactivate PAR
            CTRL -> PAM : toDTO(politicalAgentList)
            activate PAM
                PAM --> CTRL : agentDtoList
            deactivate PAM
            CTRL --> UI : agentDtoList
        deactivate CTRL

        UI --> C : shows list of agents \nand asks to select one
    deactivate UI

    C -> UI : selects a political agent
    activate UI

        UI -> CTRL : startComplaint(agentDto)
        activate CTRL
            CTRL -> AR : getCurrentUserSession()
            activate AR
                AR --> CTRL : session
            deactivate AR
            CTRL -> SESS : getUserId()
            activate SESS
                SESS --> CTRL : email
            deactivate SESS
            CTRL -> CitR : getCitizenByEmail(email.getEmail())
            activate CitR
                CitR --> CTRL : citizen
            deactivate CitR
            CTRL -> PAR : getByEmail(agentDto.getEmail())
            activate PAR
                PAR --> CTRL : politicalAgent
            deactivate PAR
            CTRL -> CPL ** : new Complaint(citizen, politicalAgent)
            CTRL --> UI : true
        deactivate CTRL
    deactivate UI

    loop for each grievance about the same agent
        UI -> CTRL : getPoliticalFunctions()
        activate UI
        activate CTRL
            CTRL --> UI : politicalFunctionList
        deactivate CTRL
        UI --> C : shows political functions and asks to select one
        deactivate UI

        C -> UI : selects a political function
        activate UI
            UI --> C : requests the complaint date and description
        deactivate UI

        C -> UI : types the complaint date and description
        activate UI
            UI --> C : shows grievance summary and requests confirmation
        deactivate UI

        C -> UI : confirms the grievance
        activate UI
            UI -> CTRL : addGrievance(description, date, function)
            activate CTRL
                CTRL -> CPL : addItem(description, date, function)
            deactivate CTRL
            UI --> C : asks to add another grievance
        deactivate UI
    end

    C -> UI : submits the complaint
    activate UI
        UI -> CTRL : submitComplaint()
        activate CTRL
            CTRL -> CR : save(cpl)
            activate CR
                CR --> CTRL : success
            deactivate CR
            CTRL --> UI : success
        deactivate CTRL
        UI --> C : displays operation success
    deactivate UI

deactivate C

@enduml
