package pt.ipp.isep.dei.ui.console;

import pt.ipp.isep.dei.controller.AssetEvolutionController;
import pt.ipp.isep.dei.domain.AssetEntry;
import pt.ipp.isep.dei.domain.AssetType;
import pt.ipp.isep.dei.domain.Declaration;
import pt.ipp.isep.dei.domain.PoliticalAgent;
import pt.ipp.isep.dei.domain.PositionEntry;
import pt.ipp.isep.dei.ui.console.utils.Utils;

import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * UI for US15 - Examine the evolution of a political agent's total assets
 * and net worth over time.
 *
 * This UI selects the agent and shows a textual summary of all declarations.
 * The graphical analysis (three evolution charts) is produced by the
 * Python script:
 *     src/main/python/us15/us15_asset_evolution.py <agent_id> [<csv_path>]
 *
 * The CSV input is generated by US24 (ExportDeclarationCsvUI).
 */
public class AssetEvolutionUI implements Runnable {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd");

    private final AssetEvolutionController controller;

    public AssetEvolutionUI() {
        controller = new AssetEvolutionController();
    }

    @Override
    public void run() {
        System.out.println("\n\n--- Asset & Net Worth Evolution (US15) --------");

        List<PoliticalAgent> agents = controller.getPoliticalAgents();
        if (agents.isEmpty()) {
            System.out.println("No political agents registered.");
            return;
        }

        PoliticalAgent agent = (PoliticalAgent) Utils.showAndSelectOne(
                agents, "Select a political agent:");
        if (agent == null) {
            System.out.println("\nOperation cancelled.");
            return;
        }

        List<Declaration> declarations = controller.getAllDeclarationsForAgent(agent);
        if (declarations.isEmpty()) {
            System.out.println("\nNo declarations found for " + agent.getName() + ".");
            return;
        }

        System.out.println("\nAgent: " + agent.getName()
                + " (ID: " + agent.getTaxIdentificationNumber() + ")");
        System.out.println("Total declarations: " + declarations.size());
        System.out.println();

        printDeclarationsTable(declarations);

        System.out.println();
        System.out.println("--- Charts ---");
        System.out.println("To generate the three evolution charts (gross salary,");
        System.out.println("side income, assets), first export the declarations CSV");
        System.out.println("via US24, then run:");
        System.out.println();
        System.out.println("  python src/main/python/us15/us15_asset_evolution.py "
                + agent.getTaxIdentificationNumber() + " <path_to_declarations.csv>");
    }

    // -------------------------------------------------------------------------
    // Text summary table
    // -------------------------------------------------------------------------

    private void printDeclarationsTable(List<Declaration> declarations) {
        String header = String.format(
                "%-12s  %-12s  %14s  %16s  %14s  %14s  %12s  %12s",
                "Date", "Type", "Gross Salary", "Side (Consult.)",
                "Side (Board)", "Real Estate", "Vehicles", "Stocks");
        System.out.println(header);
        System.out.println("-".repeat(header.length()));

        for (Declaration d : declarations) {
            String date = d.getSubmissionDate().toInstant()
                    .atZone(ZoneId.systemDefault()).toLocalDate().format(DATE_FMT);

            double grossSalary = 0, consulting = 0, board = 0;
            for (PositionEntry pe : d.getPositionEntries()) {
                grossSalary += pe.getGrossSalary();
                consulting += pe.getSideIncomeConsulting();
                board += pe.getSideIncomeBoardMemberships();
            }

            double realEstate = 0, vehicles = 0, stocks = 0;
            for (AssetEntry ae : d.getAssetEntries()) {
                if (ae.getAssetType() == AssetType.REAL_ESTATE) {
                    realEstate += ae.getAssetValue();
                } else if (ae.getAssetType() == AssetType.VEHICLES) {
                    vehicles += ae.getAssetValue();
                } else if (ae.getAssetType() == AssetType.STOCKS) {
                    stocks += ae.getAssetValue();
                }
            }

            System.out.printf(
                    "%-12s  %-12s  %14.2f  %16.2f  %14.2f  %14.2f  %12.2f  %12.2f%n",
                    date, d.getType().toString(),
                    grossSalary, consulting, board,
                    realEstate, vehicles, stocks);
        }
    }
}
