@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber
actor "Product Owner" as PO
participant ":System" as System
activate PO
    PO -> System : requests entity import from CSV file
    activate System
        System --> PO : requests CSV file path
    deactivate System
    PO -> System : provides CSV file path
    activate System
        System -> System : reads and parses CSV file
        System -> System : instantiates entities (Person, Organization, Position, Asset)
        System --> PO : displays number of entities loaded and summary
    deactivate System
@enduml
