@startuml US10-SD-partial-collect-income-data
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Journalist" as Journalist
participant ":AnalyseIncomeEvolutionUI" as UI
participant "dto:DeclarationDTO" as DEC

autonumber 11
 -> UI : display declarations
autonumber 11.1
activate UI
    group Collect Income Data

        loop for each d in declarations
            UI -> DEC : getSubmissionDate()
            activate DEC
                DEC --> UI : submissionDate
            deactivate DEC

            UI -> DEC : getType()
            activate DEC
                DEC --> UI : type
            deactivate DEC

            UI -> DEC : getIncomes()
            activate DEC
                DEC --> UI : incomes
            deactivate DEC

            UI -> DEC : getSubsidies()
            activate DEC
                DEC --> UI : subsidyEntries
            deactivate DEC
        end

        UI --> Journalist : shows declarations\nwith income evolution

    end
deactivate UI

@enduml
