@startuml US10-SD-partial-validate-period
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":AnalyseIncomeEvolutionController" as CTRL

autonumber 7
 -> CTRL : getIncomeEvolution(agent, startDate, endDate)
autonumber 7.1
activate CTRL
    group Validate Inputs

        alt agent == null
            CTRL --> CTRL : throw IllegalArgumentException("Agent cannot be null.")
        else startDate == null or endDate == null
            CTRL --> CTRL : throw IllegalArgumentException("Dates cannot be null.")
        else startDate.after(endDate) (AC2)
            CTRL --> CTRL : throw IllegalArgumentException("Start date must be before or equal to end date.")
        else valid input
            CTRL --> CTRL : ok
        end

    end
deactivate CTRL

@enduml
