@startuml US11-SD-partial-collect-assets
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":ConsultAssetsController" as CTRL
participant "d:Declaration" as DEC

autonumber 11
 -> CTRL : getAssetsAt(agent, referenceDate)
autonumber 11.1
activate CTRL
    group Collect Assets

        alt declarations is empty (AC3)
            CTRL --> CTRL : empty list
        else
            loop for each d in declarations
                CTRL -> DEC : getAssetEntries()
                activate DEC
                    DEC --> CTRL : assetEntries
                deactivate DEC
            end

            CTRL --> CTRL : assetEntries
        end

    end
    autonumber 12
    <-- CTRL : assetEntries
deactivate CTRL

note over CTRL
    AC4 (masking) is handled by
    the UI using the boolean from
    isCurrentUserJournalist().
end note

@enduml
