@startuml US11-SD-partial-get-validated-declarations-up-to
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":ConsultAssetsController" as CTRL
participant ":DeclarationRepository" as DR

autonumber 9
 -> CTRL : getAssetsAt(agent, referenceDate)
autonumber 9.1
activate CTRL
    group Get Validated Declarations For Agent Up To

        CTRL -> DR : getValidatedDeclarationsForAgentUpTo(agent, referenceDate)
        activate DR

            note right of DR
                AC2: only declarations with
                status = VALIDATED and
                submissionDate <= referenceDate
            end note

            DR --> CTRL : declarations
        deactivate DR

    end
    autonumber 10
    <-- CTRL : declarations
deactivate CTRL

@enduml
