@startuml US11-SD-partial-get-political-agents
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":ConsultAssetsController" as CTRL
participant ":PoliticalAgentRepository" as PAR
participant ":PoliticalAgentMapper" as PAM

autonumber 2
 -> CTRL : getPoliticalAgents()
autonumber 2.1
activate CTRL
    group Get Political Agents

        CTRL -> PAR : getAll()
        activate PAR
            PAR --> CTRL : agents
        deactivate PAR

        CTRL -> PAM : toDTO(agents)
        activate PAM
            PAM --> CTRL : agentsDto
        deactivate PAM

    end
    autonumber 3
    <-- CTRL : agentsDto
deactivate CTRL

@enduml
