@startuml US24-SD
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Product Owner" as PO
participant ":ExportDeclarationCsvUI" as UI
participant ":ExportDeclarationCsvController" as CTRL
participant ":DeclarationRepository" as REPO
participant ":DeclarationCsvExporter" as EXPORTER

activate PO

    PO -> UI : asks to export declaration dataset to CSV
    activate UI
        UI --> PO : requests output file path
    deactivate UI

    PO -> UI : types output file path
    activate UI

        UI -> CTRL : exportToCsv(filePath)
        activate CTRL

            CTRL -> REPO : getDeclarationsByStatus(VALIDATED)
            activate REPO
                REPO --> CTRL : validatedDeclarations
            deactivate REPO

            CTRL -> EXPORTER : export(validatedDeclarations, filePath)
            activate EXPORTER
                EXPORTER --> CTRL : success
            deactivate EXPORTER

            CTRL --> UI : success
        deactivate CTRL

        UI --> PO : displays operation (in)success
    deactivate UI

deactivate PO

@enduml
