@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US24

autonumber

actor "Product Owner" as PO
participant ":System" as System

activate PO

PO -> System : asks to export declaration dataset to CSV
activate System
System --> PO : requests output file path
deactivate System

PO -> System : types output file path
activate System
System --> PO : displays operation (in)success
deactivate System

deactivate PO

@enduml
