@startuml US09-DM
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

class EthicsCommitteeMember {
    name
    email
}

class "Political Agent" as PoliticalAgent {
    name
    email
    nationalIdentityCard
    taxIdentificationNumber
    politicalFunction
    mandateStart
    mandateEnd
}

class "Declaration of Interests" as Declaration {
    id
    name
    submissionDate
}

enum DeclarationStatus {
    PENDING
    VALIDATED
    REJECTED
}

enum Type {
    INITIAL
    REGULAR
    EXCEPTIONAL
}

enum PoliticalFunction {
    MINISTER
    DEPUTY
    COUNCILLOR
    PARISH_COUNCIL_PRESIDENT
    MAYOR
}

class Income {
    amount
    source
    institution
    date
}

class Asset {
    acquisitionValue
    marketValue
}

class "Real Estate" as RealEstate {
    description
}

class PositionEntry {
    remuneration
    startDate
    endDate
}

class BusinessParticipation {
    numberOfShares
    marketValue
}

EthicsCommitteeMember "*" -- "*" PoliticalAgent : consults

PoliticalAgent "*" -- "*" Declaration : has

PoliticalAgent "1" -- "1" PoliticalFunction : has

Declaration "1" -- "1" Type : has
Declaration "1" -- "1" DeclarationStatus : has
Declaration "1" -- "*" Income : has
Declaration "1" -- "*" Asset : has

Declaration "1" -- "*" PositionEntry : has
Declaration "1" -- "*" BusinessParticipation : has

Asset "1" -- "1" RealEstate : can be

@enduml
