@startuml US10-DM
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

class Journalist {
    name
    email
    phone
}

class "Political Agent" as PoliticalAgent {
    name
    politicalFunction
    mandateStart
    mandateEnd
}

class "Declaration of Interests" as Declaration {
    id
    name
    position
    submissionDate
}

enum Type {
    Initial
    Regular
    Exceptional
}

class Income {
    amount
    source
    date
}

Journalist "*" -- "*" Income : analyses

PoliticalAgent "*" -- "*" Declaration : has

Declaration "1" -- "1" Type : has
Declaration "1" -- "*" Income : has

@enduml
